#
# https://www.appveyor.com/docs/appveyor-yml
#

os: Visual Studio 2015

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  # C:\projects\kafka-net
  - echo %CD%
  # C:\projects\kafka-net\Kafka.NET
  - ps: cd Kafka.NET
  - echo %CD%

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"

build_script:
  - echo %CD%
  - msbuild Kafka.NET.csproj /t:Rebuild /p:Platform=AnyCPU /p:Configuration=Release
  - msbuild Kafka.NET.csproj /t:Rebuild /p:Platform=AnyCPU /p:Configuration=Release46
  - msbuild Kafka.NET.csproj /t:Rebuild /p:Platform=AnyCPU /p:Configuration=Release45
